config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root "home#index"
  get "home/about"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  #allow_browser versions: :modern
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy!

    respond_to do |format|
      format.html { redirect_to pins_path, status: :see_other, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.expect(pin: [ :description ])
  end
  def correct_user
    @pin = correct_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Minitravels', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', home_about_path %></li>
            <li><%= link_to 'List Pins', pins_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Add Pin', new_pin_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>  
            <% else %>
              <li><%= link_to "Login", new_user_session_path %></li>
              <li><%= link_to "Join", new_user_registration_path %></li>
            <% end %>  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/about.html.erb
<h1>About me</h1>
<p>My name is Eliab and I'm building a Minitravels Site</p>

app/views/home/index.html.erb
<div class="jumbotron">
    <h1>Home#index</h1>
    <p>Minitravels</p>
    <%= link_to 'About', home_about_path, class:'btn btn-default btn-lg' %>
    <%= link_to 'Home', root_path, class:'btn btn-primary btn-lg' %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Minitravels" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'home/header' %>

  <div class="container">  
  <% flash.each do | name, msg | %>
    <%= content_tag(:div, msg, class:"alert alter-info") %>
    <% end %>
  <%= yield %>
  </div>
  
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_with(model: pin) do |form| %>
  <% if pin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>
      <ul>
        <% pin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading"><%= form.label :description, style: "display: block" %></div>
      <div class="panel-body">
        <%= form.text_field :description %>  
      </div>
      <div class="panel-footer">
        <%= form.submit %> 
      </div>   
    </div>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>" class="panel panel-default">
  <strong>Description:</strong>
  <h3><%= pin.description %></h3>
  <% if pin.user == current_user %> <%= link_to 'Show', pin %> <% end %>
</div>

app/views/pins/edit.html.erb
<% content_for :title, "Editing pin" %>

<div class="panel panel-default">
  <div class="panel-heading"><h1>Editing pin</h1></div>
    <div class="panel-body">
      <%= render "form", pin: @pin %>
    </div>
    <div class="panel-footer">
    
  </div>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p> 
<% content_for :title, "Pins" %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Pins</h3>
  </div>
  <div class="panel-body">
    <div id="pins">
      <% @pins.each do |pin| %>
        <%= render pin %>
      <% end %>
    </div>
  </div>

  

      
      
  
  
  

</div>

app/views/pins/new.html.erb
<% content_for :title, "New pin" %>

<div class="panel panel-default">
  <div class="panel-heading">
      <h1>New pin</h1>
  </div>
  <div class="panel-body">
      <%= render "form", pin: @pin %>
      <div class="panel-footer">
        <%= link_to "Back to pins", pins_path %>
      </div>
  </div>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading"><%= render @pin %>
  <%= link_to "Edit this pin", edit_pin_path(@pin) %> | <%= link_to "Back to pins", pins_path %>
  </div>


<div class="panel-footer">
<%= button_to "Destroy this pin", @pin, method: :delete %>
</div>

</div>